[package]
name = "arb-tob"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
arb-core = { path = "../arb-core" }
arb-query = { path = "../arb-query" }
parquet = { version = "56", default-features = false, features = ["zstd"] }
