#!/usr/bin/env python3
"""Generate signing-parity fixtures for the Rust arb-venue crate.

Uses THROWAWAY keys generated in-memory — it NEVER reads ~/.arbbot-credentials
or any credentials dir. It signs a handful of representative money-path requests
through the REAL Python signing code paths (arbbot.record.kalshi.sign_headers
for Kalshi RSA-PSS; PolymarketUsOrderGateway._headers for PM-US Ed25519) and
records message + key material + signature + the exact header dict, so the Rust
tests can (a) verify the Python RSA-PSS signature, (b) byte-compare the
deterministic Ed25519 signature, and (c) assert header composition byte-match.

Run from the worktree root with the project venv:
    PYTHONPATH=src /home/geoff/claude/arbbot/.venv/bin/python scripts/venue_sig_fixtures.py

Output: rust/crates/arb-venue/tests/fixtures/venue/sigs.json (committed).
"""

from __future__ import annotations

import base64
import json
import os
import pathlib

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ed25519, rsa

from arbbot.record.kalshi import sign_headers
from arbbot.exec.polymarket_us_gateway import PolymarketUsOrderGateway

OUT = (pathlib.Path(__file__).resolve().parent.parent
       / "rust/crates/arb-venue/tests/fixtures/venue/sigs.json")

# Representative money-path requests. path == the exact string each Python
# client signs (Kalshi prepends the /trade-api/v2 version prefix; PM-US signs
# the bare /v1 path). Query strings are NEVER signed on either venue.
KALSHI_REQS = [
    ("place",     "POST",   "/trade-api/v2/portfolio/events/orders"),
    ("cancel",    "DELETE", "/trade-api/v2/portfolio/events/orders/ORDER123"),
    ("list",      "GET",    "/trade-api/v2/portfolio/orders"),
    ("balance",   "GET",    "/trade-api/v2/portfolio/balance"),
    ("positions", "GET",    "/trade-api/v2/portfolio/positions"),
]
PMUS_REQS = [
    ("place",      "POST", "/v1/orders"),
    ("cancel",     "POST", "/v1/order/ORDER123/cancel"),
    ("cancel_all", "POST", "/v1/orders/open/cancel"),
    ("balances",   "GET",  "/v1/account/balances"),
    ("positions",  "GET",  "/v1/portfolio/positions"),
]

KALSHI_KID = "test-kalshi-key-id"
PMUS_KID = "test-pmus-key-id"


def build_kalshi():
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    priv_pem = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    ).decode()
    pub_pem = key.public_key().public_bytes(
        serialization.Encoding.PEM,
        serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode()

    cases = []
    for name, method, path in KALSHI_REQS:
        # REAL code path: sign_headers composes ts + METHOD + path and signs
        # RSA-PSS(SHA256, salt=DIGEST_LENGTH). ts is read back from the header so
        # the recorded message matches the recorded signature exactly.
        headers = sign_headers(KALSHI_KID, key, method, path)
        ts = headers["KALSHI-ACCESS-TIMESTAMP"]
        cases.append({
            "name": name, "method": method, "path": path,
            "timestamp_ms": ts,
            "message": ts + method + path,
            "signature_b64": headers["KALSHI-ACCESS-SIGNATURE"],
            "headers": headers,
        })
    return {
        "api_key_id": KALSHI_KID,
        "private_key_pkcs8_pem": priv_pem,
        "public_key_spki_pem": pub_pem,
        "cases": cases,
    }


def build_pmus():
    seed = os.urandom(32)
    secret_b64 = base64.b64encode(seed).decode()
    priv = ed25519.Ed25519PrivateKey.from_private_bytes(seed)
    pub_raw = priv.public_key().public_bytes(
        serialization.Encoding.Raw, serialization.PublicFormat.Raw)

    # Construct the REAL gateway (dry-run; no network) and sign through its
    # _headers — the exact production Ed25519 path.
    gw = PolymarketUsOrderGateway(PMUS_KID, secret_b64, live=False)

    cases = []
    for name, method, path in PMUS_REQS:
        headers = gw._headers(method, path)
        ts = headers["X-PM-Timestamp"]
        sig_b64 = headers["X-PM-Signature"]
        cases.append({
            "name": name, "method": method, "path": path,
            "timestamp_ms": ts,
            "message": ts + method + path,
            "signature_b64": sig_b64,
            "signature_hex": base64.b64decode(sig_b64).hex(),
            "headers": headers,
        })
    return {
        "api_key_id": PMUS_KID,
        "seed_hex": seed.hex(),
        "public_key_hex": pub_raw.hex(),
        "cases": cases,
    }


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    doc = {
        "_note": "THROWAWAY test keys only — generated by scripts/venue_sig_fixtures.py. "
                 "Not real credentials. RSA-PSS signatures are salted "
                 "(nondeterministic); Ed25519 signatures are deterministic.",
        "kalshi": build_kalshi(),
        "pmus": build_pmus(),
    }
    OUT.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"wrote {OUT} "
          f"({len(doc['kalshi']['cases'])} kalshi + {len(doc['pmus']['cases'])} pmus cases)")


if __name__ == "__main__":
    main()
